Lesson2
Bigstation/geekshop pull request #2
Opened 2021-01-28 16:28 UTC by Bigstation

2021-01-29 09:17 UTC, Vokler requested changes

2021-01-29 09:17 UTC, Vokler commented on mainapp/views.py
> +        'data': datetime.date.today(),
Добавьте в context список продуктов, как мы делали это на уроке. Чтобы в products.html избавиться от повторяющихся блоков и занести все в цикл for

2021-01-29 10:40 UTC, Bigstation commented on mainapp/views.py
> +        'data': datetime.date.today(),
Готово, проверьте пжл

2021-01-29 10:43 UTC, Bigstation commented on mainapp/views.py
> +        'data': datetime.date.today(),
Вопрос по гиту: после внесения изменений в ветку Lesson2 уже нет необходимости делать PR ?

2021-01-30 10:47 UTC, Vokler commented on mainapp/views.py
> +        'data': datetime.date.today(),
Нет, делается PR один раз, а потом уже я вижу когда вы вносите изменения

2021-01-30 10:48 UTC, merged